/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AppConstantsEnumsPiece } from './AppConstantsEnumsPiece';
import {
    AppConstantsEnumsPieceFromJSON,
    AppConstantsEnumsPieceFromJSONTyped,
    AppConstantsEnumsPieceToJSON,
} from './AppConstantsEnumsPiece';
import type { Color } from './Color';
import {
    ColorFromJSON,
    ColorFromJSONTyped,
    ColorToJSON,
} from './Color';

/**
 * 
 * @export
 * @interface AppSchemasGameSchemaPiece
 */
export interface AppSchemasGameSchemaPiece {
    /**
     * 
     * @type {AppConstantsEnumsPiece}
     * @memberof AppSchemasGameSchemaPiece
     */
    piece: AppConstantsEnumsPiece;
    /**
     * 
     * @type {Color}
     * @memberof AppSchemasGameSchemaPiece
     */
    color: Color;
    /**
     * 
     * @type {number}
     * @memberof AppSchemasGameSchemaPiece
     */
    index: number;
}

/**
 * Check if a given object implements the AppSchemasGameSchemaPiece interface.
 */
export function instanceOfAppSchemasGameSchemaPiece(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "piece" in value;
    isInstance = isInstance && "color" in value;
    isInstance = isInstance && "index" in value;

    return isInstance;
}

export function AppSchemasGameSchemaPieceFromJSON(json: any): AppSchemasGameSchemaPiece {
    return AppSchemasGameSchemaPieceFromJSONTyped(json, false);
}

export function AppSchemasGameSchemaPieceFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSchemasGameSchemaPiece {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'piece': AppConstantsEnumsPieceFromJSON(json['piece']),
        'color': ColorFromJSON(json['color']),
        'index': json['index'],
    };
}

export function AppSchemasGameSchemaPieceToJSON(value?: AppSchemasGameSchemaPiece | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'piece': AppConstantsEnumsPieceToJSON(value.piece),
        'color': ColorToJSON(value.color),
        'index': value.index,
    };
}

