/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthTokens
 */
export interface AuthTokens {
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    tokenType?: string;
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    accessToken?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AuthTokens
     */
    refreshToken?: string | null;
}

/**
 * Check if a given object implements the AuthTokens interface.
 */
export function instanceOfAuthTokens(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function AuthTokensFromJSON(json: any): AuthTokens {
    return AuthTokensFromJSONTyped(json, false);
}

export function AuthTokensFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthTokens {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'tokenType': !exists(json, 'token_type') ? undefined : json['token_type'],
        'accessToken': !exists(json, 'access_token') ? undefined : json['access_token'],
        'refreshToken': !exists(json, 'refresh_token') ? undefined : json['refresh_token'],
    };
}

export function AuthTokensToJSON(value?: AuthTokens | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token_type': value.tokenType,
        'access_token': value.accessToken,
        'refresh_token': value.refreshToken,
    };
}

