/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditableProfile
 */
export interface EditableProfile {
    /**
     * 
     * @type {string}
     * @memberof EditableProfile
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof EditableProfile
     */
    about?: string;
}

/**
 * Check if a given object implements the EditableProfile interface.
 */
export function instanceOfEditableProfile(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EditableProfileFromJSON(json: any): EditableProfile {
    return EditableProfileFromJSONTyped(json, false);
}

export function EditableProfileFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditableProfile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'country': !exists(json, 'country') ? undefined : json['country'],
        'about': !exists(json, 'about') ? undefined : json['about'],
    };
}

export function EditableProfileToJSON(value?: EditableProfile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'country': value.country,
        'about': value.about,
    };
}

