/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseDictStrStr
 */
export interface ErrorResponseDictStrStr {
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ErrorResponseDictStrStr
     */
    details: { [key: string]: string; };
}

/**
 * Check if a given object implements the ErrorResponseDictStrStr interface.
 */
export function instanceOfErrorResponseDictStrStr(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "details" in value;

    return isInstance;
}

export function ErrorResponseDictStrStrFromJSON(json: any): ErrorResponseDictStrStr {
    return ErrorResponseDictStrStrFromJSONTyped(json, false);
}

export function ErrorResponseDictStrStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseDictStrStr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': json['details'],
    };
}

export function ErrorResponseDictStrStrToJSON(value?: ErrorResponseDictStrStr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': value.details,
    };
}

