/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseStr
 */
export interface ErrorResponseStr {
    /**
     * 
     * @type {string}
     * @memberof ErrorResponseStr
     */
    details: string;
}

/**
 * Check if a given object implements the ErrorResponseStr interface.
 */
export function instanceOfErrorResponseStr(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "details" in value;

    return isInstance;
}

export function ErrorResponseStrFromJSON(json: any): ErrorResponseStr {
    return ErrorResponseStrFromJSONTyped(json, false);
}

export function ErrorResponseStrFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseStr {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'details': json['details'],
    };
}

export function ErrorResponseStrToJSON(value?: ErrorResponseStr | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'details': value.details,
    };
}

