/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { GameResult } from './GameResult';
import {
    GameResultFromJSON,
    GameResultFromJSONTyped,
    GameResultToJSON,
} from './GameResult';
import type { PublicUserOut } from './PublicUserOut';
import {
    PublicUserOutFromJSON,
    PublicUserOutFromJSONTyped,
    PublicUserOutToJSON,
} from './PublicUserOut';
import type { Variant } from './Variant';
import {
    VariantFromJSON,
    VariantFromJSONTyped,
    VariantToJSON,
} from './Variant';

/**
 * 
 * @export
 * @interface FinishedGame
 */
export interface FinishedGame {
    /**
     * 
     * @type {string}
     * @memberof FinishedGame
     */
    token: string;
    /**
     * 
     * @type {PublicUserOut}
     * @memberof FinishedGame
     */
    userWhite: PublicUserOut | null;
    /**
     * 
     * @type {PublicUserOut}
     * @memberof FinishedGame
     */
    userBlack: PublicUserOut | null;
    /**
     * 
     * @type {GameResult}
     * @memberof FinishedGame
     */
    results: GameResult;
    /**
     * 
     * @type {Variant}
     * @memberof FinishedGame
     */
    variant: Variant;
    /**
     * 
     * @type {number}
     * @memberof FinishedGame
     */
    timeControl: number;
    /**
     * 
     * @type {number}
     * @memberof FinishedGame
     */
    increment: number;
    /**
     * 
     * @type {Date}
     * @memberof FinishedGame
     */
    createdAt: Date;
}

/**
 * Check if a given object implements the FinishedGame interface.
 */
export function instanceOfFinishedGame(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "token" in value;
    isInstance = isInstance && "userWhite" in value;
    isInstance = isInstance && "userBlack" in value;
    isInstance = isInstance && "results" in value;
    isInstance = isInstance && "variant" in value;
    isInstance = isInstance && "timeControl" in value;
    isInstance = isInstance && "increment" in value;
    isInstance = isInstance && "createdAt" in value;

    return isInstance;
}

export function FinishedGameFromJSON(json: any): FinishedGame {
    return FinishedGameFromJSONTyped(json, false);
}

export function FinishedGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): FinishedGame {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'token': json['token'],
        'userWhite': PublicUserOutFromJSON(json['user_white']),
        'userBlack': PublicUserOutFromJSON(json['user_black']),
        'results': GameResultFromJSON(json['results']),
        'variant': VariantFromJSON(json['variant']),
        'timeControl': json['time_control'],
        'increment': json['increment'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function FinishedGameToJSON(value?: FinishedGame | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'token': value.token,
        'user_white': PublicUserOutToJSON(value.userWhite),
        'user_black': PublicUserOutToJSON(value.userBlack),
        'results': GameResultToJSON(value.results),
        'variant': VariantToJSON(value.variant),
        'time_control': value.timeControl,
        'increment': value.increment,
        'created_at': (value.createdAt.toISOString()),
    };
}

