/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameResult = {
    White: 'white',
    Black: 'black',
    Draw: 'draw'
} as const;
export type GameResult = typeof GameResult[keyof typeof GameResult];


export function GameResultFromJSON(json: any): GameResult {
    return GameResultFromJSONTyped(json, false);
}

export function GameResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameResult {
    return json as GameResult;
}

export function GameResultToJSON(value?: GameResult | null): any {
    return value as any;
}

