/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum PieceType {
    King = 'king',
    Queen = 'queen',
    Rook = 'rook',
    Knook = 'knook',
    Xook = 'xook',
    Antiqueen = 'antiqueen',
    Archbishop = 'archbishop',
    Bishop = 'bishop',
    Horse = 'horse',
    Pawn = 'pawn',
    ChildPawn = 'child_pawn'
}


export function PieceTypeFromJSON(json: any): PieceType {
    return PieceTypeFromJSONTyped(json, false);
}

export function PieceTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): PieceType {
    return json as PieceType;
}

export function PieceTypeToJSON(value?: PieceType | null): any {
    return value as any;
}

