/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateUserOut
 */
export interface PrivateUserOut {
    /**
     * 
     * @type {number}
     * @memberof PrivateUserOut
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    about: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    country: string | null;
    /**
     * 
     * @type {Date}
     * @memberof PrivateUserOut
     */
    pfpLastChanged: Date;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof PrivateUserOut
     */
    usernameLastChanged: Date | null;
}

/**
 * Check if a given object implements the PrivateUserOut interface.
 */
export function instanceOfPrivateUserOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "about" in value;
    isInstance = isInstance && "country" in value;
    isInstance = isInstance && "pfpLastChanged" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "usernameLastChanged" in value;

    return isInstance;
}

export function PrivateUserOutFromJSON(json: any): PrivateUserOut {
    return PrivateUserOutFromJSONTyped(json, false);
}

export function PrivateUserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateUserOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'username': json['username'],
        'about': json['about'],
        'country': json['country'],
        'pfpLastChanged': (new Date(json['pfp_last_changed'])),
        'email': json['email'],
        'usernameLastChanged': (json['username_last_changed'] === null ? null : new Date(json['username_last_changed'])),
    };
}

export function PrivateUserOutToJSON(value?: PrivateUserOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'username': value.username,
        'about': value.about,
        'country': value.country,
        'pfp_last_changed': (value.pfpLastChanged.toISOString()),
        'email': value.email,
        'username_last_changed': (value.usernameLastChanged === null ? null : value.usernameLastChanged.toISOString()),
    };
}

