/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Rating
 */
export interface Rating {
    /**
     * 
     * @type {number}
     * @memberof Rating
     */
    elo: number;
    /**
     * 
     * @type {Date}
     * @memberof Rating
     */
    achievedAt: Date;
}

/**
 * Check if a given object implements the Rating interface.
 */
export function instanceOfRating(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "elo" in value;
    isInstance = isInstance && "achievedAt" in value;

    return isInstance;
}

export function RatingFromJSON(json: any): Rating {
    return RatingFromJSONTyped(json, false);
}

export function RatingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Rating {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'elo': json['elo'],
        'achievedAt': (new Date(json['achieved_at'])),
    };
}

export function RatingToJSON(value?: Rating | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'elo': value.elo,
        'achieved_at': (value.achievedAt.toISOString()),
    };
}

