/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Rating } from './Rating';
import {
    RatingFromJSON,
    RatingFromJSONTyped,
    RatingToJSON,
} from './Rating';
import type { RatingOverview } from './RatingOverview';
import {
    RatingOverviewFromJSON,
    RatingOverviewFromJSONTyped,
    RatingOverviewToJSON,
} from './RatingOverview';

/**
 * 
 * @export
 * @interface ResponseProfileGetRatingsHistory
 */
export interface ResponseProfileGetRatingsHistory {
    /**
     * 
     * @type {number}
     * @memberof ResponseProfileGetRatingsHistory
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseProfileGetRatingsHistory
     */
    max: number;
    /**
     * 
     * @type {number}
     * @memberof ResponseProfileGetRatingsHistory
     */
    current: number;
    /**
     * 
     * @type {Array<Rating>}
     * @memberof ResponseProfileGetRatingsHistory
     */
    history: Array<Rating>;
}

/**
 * Check if a given object implements the ResponseProfileGetRatingsHistory interface.
 */
export function instanceOfResponseProfileGetRatingsHistory(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "min" in value;
    isInstance = isInstance && "max" in value;
    isInstance = isInstance && "current" in value;
    isInstance = isInstance && "history" in value;

    return isInstance;
}

export function ResponseProfileGetRatingsHistoryFromJSON(json: any): ResponseProfileGetRatingsHistory {
    return ResponseProfileGetRatingsHistoryFromJSONTyped(json, false);
}

export function ResponseProfileGetRatingsHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseProfileGetRatingsHistory {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'min': json['min'],
        'max': json['max'],
        'current': json['current'],
        'history': ((json['history'] as Array<any>).map(RatingFromJSON)),
    };
}

export function ResponseProfileGetRatingsHistoryToJSON(value?: ResponseProfileGetRatingsHistory | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'min': value.min,
        'max': value.max,
        'current': value.current,
        'history': ((value.history as Array<any>).map(RatingToJSON)),
    };
}

