/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SimpleUserOut
 */
export interface SimpleUserOut {
    /**
     * 
     * @type {number}
     * @memberof SimpleUserOut
     */
    userId: number;
    /**
     * 
     * @type {string}
     * @memberof SimpleUserOut
     */
    username: string;
}

/**
 * Check if a given object implements the SimpleUserOut interface.
 */
export function instanceOfSimpleUserOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "username" in value;

    return isInstance;
}

export function SimpleUserOutFromJSON(json: any): SimpleUserOut {
    return SimpleUserOutFromJSONTyped(json, false);
}

export function SimpleUserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): SimpleUserOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'userId': json['user_id'],
        'username': json['username'],
    };
}

export function SimpleUserOutToJSON(value?: SimpleUserOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'user_id': value.userId,
        'username': value.username,
    };
}

