/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOut
 */
export interface UserOut {
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    about?: string;
    /**
     * 
     * @type {number}
     * @memberof UserOut
     */
    userId: number;
    /**
     * 
     * @type {Date}
     * @memberof UserOut
     */
    pfpLastChanged?: Date;
}

/**
 * Check if a given object implements the UserOut interface.
 */
export function instanceOfUserOut(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "userId" in value;

    return isInstance;
}

export function UserOutFromJSON(json: any): UserOut {
    return UserOutFromJSONTyped(json, false);
}

export function UserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOut {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'about': !exists(json, 'about') ? undefined : json['about'],
        'userId': json['user_id'],
        'pfpLastChanged': !exists(json, 'pfp_last_changed') ? undefined : (new Date(json['pfp_last_changed'])),
    };
}

export function UserOutToJSON(value?: UserOut | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'country': value.country,
        'about': value.about,
        'user_id': value.userId,
        'pfp_last_changed': value.pfpLastChanged === undefined ? undefined : (value.pfpLastChanged.toISOString()),
    };
}

