/* tslint:disable */
/* eslint-disable */
/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOutSensitive
 */
export interface UserOutSensitive {
    /**
     * 
     * @type {string}
     * @memberof UserOutSensitive
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutSensitive
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserOutSensitive
     */
    country?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOutSensitive
     */
    about?: string;
    /**
     * 
     * @type {number}
     * @memberof UserOutSensitive
     */
    userId: number;
    /**
     * 
     * @type {Date}
     * @memberof UserOutSensitive
     */
    pfpLastChanged: Date;
}

/**
 * Check if a given object implements the UserOutSensitive interface.
 */
export function instanceOfUserOutSensitive(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "username" in value;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "userId" in value;
    isInstance = isInstance && "pfpLastChanged" in value;

    return isInstance;
}

export function UserOutSensitiveFromJSON(json: any): UserOutSensitive {
    return UserOutSensitiveFromJSONTyped(json, false);
}

export function UserOutSensitiveFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOutSensitive {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': json['username'],
        'email': json['email'],
        'country': !exists(json, 'country') ? undefined : json['country'],
        'about': !exists(json, 'about') ? undefined : json['about'],
        'userId': json['user_id'],
        'pfpLastChanged': (new Date(json['pfp_last_changed'])),
    };
}

export function UserOutSensitiveToJSON(value?: UserOutSensitive | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'email': value.email,
        'country': value.country,
        'about': value.about,
        'user_id': value.userId,
        'pfp_last_changed': (value.pfpLastChanged.toISOString()),
    };
}

