// <auto-generated />
using System;
using AnarchyChess.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AnarchyChess.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260515121833_Vote")]
    partial class Vote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AnarchyChess.Api.ArchivedGames.Entities.GameArchive", b =>
                {
                    b.Property<string>("GameToken")
                        .HasColumnType("text")
                        .HasColumnName("game_token");

                    b.Property<int>("BaseSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("base_seconds");

                    b.Property<int>("BlackPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("black_player_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("IncrementSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("increment_seconds");

                    b.Property<bool>("IsBotGame")
                        .HasColumnType("boolean")
                        .HasColumnName("is_bot_game");

                    b.Property<int>("PoolType")
                        .HasColumnType("integer")
                        .HasColumnName("pool_type");

                    b.Property<int>("Result")
                        .HasColumnType("integer")
                        .HasColumnName("result");

                    b.Property<string>("ResultDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("result_description");

                    b.Property<int>("WhitePlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("white_player_id");

                    b.HasKey("GameToken")
                        .HasName("pk_game_archives");

                    b.HasIndex("BlackPlayerId")
                        .HasDatabaseName("ix_game_archives_black_player_id");

                    b.HasIndex("WhitePlayerId")
                        .HasDatabaseName("ix_game_archives_white_player_id");

                    b.ToTable("game_archives", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.ArchivedGames.Entities.PlayerArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Color")
                        .HasColumnType("integer")
                        .HasColumnName("color");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_player_archives");

                    b.ToTable("player_archives", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Auth.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revoked");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("jti");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_tokens");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_refresh_tokens_user_id");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Game.Entities.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("GameToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("game_token");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_messages_logs");

                    b.ToTable("messages_logs", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Preferences.Entities.UserPreferences", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallengePreference")
                        .HasColumnType("integer")
                        .HasColumnName("challenge_preference");

                    b.Property<bool>("ShowChat")
                        .HasColumnType("boolean")
                        .HasColumnName("show_chat");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_preferences");

                    b.ToTable("user_preferences", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Profile.Entities.AuthedUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("about");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("country_code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_banned");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.Property<DateTime?>("UsernameLastChanged")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("username_last_changed");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Quests.Entities.UserQuestPoints", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("MonthlyPoints")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_points");

                    b.Property<int>("TotalPoints")
                        .HasColumnType("integer")
                        .HasColumnName("total_points");

                    b.HasKey("UserId")
                        .HasName("pk_quest_points");

                    b.ToTable("quest_points", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Social.Entities.BlockedUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BlockedUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("blocked_user_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_blocked_users");

                    b.HasIndex("BlockedUserId")
                        .HasDatabaseName("ix_blocked_users_blocked_user_id");

                    b.HasIndex("UserId", "BlockedUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_blocked_users_user_id_blocked_user_id");

                    b.ToTable("blocked_users", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Social.Entities.StarredUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("StarredUserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("starred_user_id");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_starred_users");

                    b.HasIndex("StarredUserId")
                        .HasDatabaseName("ix_starred_users_starred_user_id");

                    b.HasIndex("UserId", "StarredUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_starred_users_user_id_starred_user_id");

                    b.ToTable("starred_users", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.UserRating.Entities.CurrentRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("TimeControl")
                        .HasColumnType("integer")
                        .HasColumnName("time_control");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_current_ratings");

                    b.ToTable("current_ratings", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.UserRating.Entities.RatingArchive", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AchievedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("achieved_at");

                    b.Property<int>("TimeControl")
                        .HasColumnType("integer")
                        .HasColumnName("time_control");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_rating_archives");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_rating_archives_user_id");

                    b.ToTable("rating_archives", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.PendingUserVote", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("VotePairId")
                        .HasColumnType("integer")
                        .HasColumnName("vote_pair_id");

                    b.HasKey("UserId")
                        .HasName("pk_pending_user_votes");

                    b.HasIndex("VotePairId")
                        .HasDatabaseName("ix_pending_user_votes_vote_pair_id");

                    b.ToTable("pending_user_votes", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.UserVote", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<int>("VotePairId")
                        .HasColumnType("integer")
                        .HasColumnName("vote_pair_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ip_address");

                    b.Property<bool>("PickedOptionA")
                        .HasColumnType("boolean")
                        .HasColumnName("picked_option_a");

                    b.Property<float>("VoteWeight")
                        .HasColumnType("real")
                        .HasColumnName("vote_weight");

                    b.HasKey("UserId", "VotePairId")
                        .HasName("pk_user_votes");

                    b.HasIndex("IpAddress")
                        .HasDatabaseName("ix_user_votes_ip_address");

                    b.HasIndex("VotePairId")
                        .HasDatabaseName("ix_user_votes_vote_pair_id");

                    b.ToTable("user_votes", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.VoteOption", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Key")
                        .HasName("pk_vote_options");

                    b.ToTable("vote_options", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.VoteOptionPair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("OptionAKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_a_key");

                    b.Property<string>("OptionBKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("option_b_key");

                    b.HasKey("Id")
                        .HasName("pk_vote_option_pairs");

                    b.HasIndex("OptionBKey")
                        .HasDatabaseName("ix_vote_option_pairs_option_b_key");

                    b.HasIndex("OptionAKey", "OptionBKey")
                        .IsUnique()
                        .HasDatabaseName("ix_vote_option_pairs_option_a_key_option_b_key");

                    b.ToTable("vote_option_pairs", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AnarchyChess.Api.ArchivedGames.Entities.GameArchive", b =>
                {
                    b.HasOne("AnarchyChess.Api.ArchivedGames.Entities.PlayerArchive", "BlackPlayer")
                        .WithMany()
                        .HasForeignKey("BlackPlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_archives_player_archives_black_player_id");

                    b.HasOne("AnarchyChess.Api.ArchivedGames.Entities.PlayerArchive", "WhitePlayer")
                        .WithMany()
                        .HasForeignKey("WhitePlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_archives_player_archives_white_player_id");

                    b.Navigation("BlackPlayer");

                    b.Navigation("WhitePlayer");
                });

            modelBuilder.Entity("AnarchyChess.Api.Auth.Entities.RefreshToken", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_tokens_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnarchyChess.Api.Quests.Entities.UserQuestPoints", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quest_points_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AnarchyChess.Api.Social.Entities.BlockedUser", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", "Blocked")
                        .WithMany()
                        .HasForeignKey("BlockedUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_blocked_users_users_blocked_user_id");

                    b.Navigation("Blocked");
                });

            modelBuilder.Entity("AnarchyChess.Api.Social.Entities.StarredUser", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", "Starred")
                        .WithMany()
                        .HasForeignKey("StarredUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_starred_users_users_starred_user_id");

                    b.Navigation("Starred");
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.PendingUserVote", b =>
                {
                    b.HasOne("AnarchyChess.Api.Vote.Entities.VoteOptionPair", "VotePair")
                        .WithMany()
                        .HasForeignKey("VotePairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pending_user_votes_vote_option_pairs_vote_pair_id");

                    b.Navigation("VotePair");
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.UserVote", b =>
                {
                    b.HasOne("AnarchyChess.Api.Vote.Entities.VoteOptionPair", "VotePair")
                        .WithMany()
                        .HasForeignKey("VotePairId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_votes_vote_option_pairs_vote_pair_id");

                    b.Navigation("VotePair");
                });

            modelBuilder.Entity("AnarchyChess.Api.Vote.Entities.VoteOptionPair", b =>
                {
                    b.HasOne("AnarchyChess.Api.Vote.Entities.VoteOption", "OptionA")
                        .WithMany()
                        .HasForeignKey("OptionAKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vote_option_pairs_vote_options_option_a_key");

                    b.HasOne("AnarchyChess.Api.Vote.Entities.VoteOption", "OptionB")
                        .WithMany()
                        .HasForeignKey("OptionBKey")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_vote_option_pairs_vote_options_option_b_key");

                    b.Navigation("OptionA");

                    b.Navigation("OptionB");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<AnarchyChess.Api.Profile.Models.UserId>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<AnarchyChess.Api.Profile.Models.UserId>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<AnarchyChess.Api.Profile.Models.UserId>", b =>
                {
                    b.HasOne("AnarchyChess.Api.Profile.Entities.AuthedUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });
#pragma warning restore 612, 618
        }
    }
}
