// This file is auto-generated by @hey-api/openapi-ts

import type {
    Options as ClientOptions,
    TDataShape,
    Client,
} from "@hey-api/client-next";
import type {
    SignupData,
    SignupResponse,
    SignupError,
    SigninData,
    SigninResponse,
    SigninError,
    RefreshData,
    RefreshResponse,
    RefreshError,
    CreatesGuestUserData,
    CreatesGuestUserResponse,
    TestAuthedData,
    TestAuthedResponse,
    TestAuthedError,
    TestGuestData,
    TestGuestResponse,
    TestGuestError,
    GetAuthedUserData,
    GetAuthedUserResponse,
    GetAuthedUserError,
    GetUserData,
    GetUserResponse,
    GetUserError,
    EditProfileSettingsData,
    EditProfileSettingsResponse,
    EditProfileSettingsError,
    EditUsernameData,
    EditUsernameResponse,
    EditUsernameError,
} from "./types.gen";
import { client as _heyApiClient } from "./client.gen";

export type Options<
    TData extends TDataShape = TDataShape,
    ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const signup = <ThrowOnError extends boolean = false>(
    options?: Options<SignupData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        SignupResponse,
        SignupError,
        ThrowOnError
    >({
        url: "/api/Auth/signup",
        ...options,
        headers: {
            "Content-Type": "application/json-patch+json",
            ...options?.headers,
        },
    });
};

export const signin = <ThrowOnError extends boolean = false>(
    options?: Options<SigninData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        SigninResponse,
        SigninError,
        ThrowOnError
    >({
        url: "/api/Auth/signin",
        ...options,
        headers: {
            "Content-Type": "application/json-patch+json",
            ...options?.headers,
        },
    });
};

export const refresh = <ThrowOnError extends boolean = false>(
    options?: Options<RefreshData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        RefreshResponse,
        RefreshError,
        ThrowOnError
    >({
        url: "/api/Auth/refresh",
        ...options,
    });
};

export const createsGuestUser = <ThrowOnError extends boolean = false>(
    options?: Options<CreatesGuestUserData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        CreatesGuestUserResponse,
        unknown,
        ThrowOnError
    >({
        url: "/api/Auth/guest",
        ...options,
    });
};

export const testAuthed = <ThrowOnError extends boolean = false>(
    options?: Options<TestAuthedData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        TestAuthedResponse,
        TestAuthedError,
        ThrowOnError
    >({
        url: "/api/Auth/test-authed",
        ...options,
    });
};

export const testGuest = <ThrowOnError extends boolean = false>(
    options?: Options<TestGuestData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).post<
        TestGuestResponse,
        TestGuestError,
        ThrowOnError
    >({
        url: "/api/Auth/test-guest",
        ...options,
    });
};

export const getAuthedUser = <ThrowOnError extends boolean = false>(
    options?: Options<GetAuthedUserData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).get<
        GetAuthedUserResponse,
        GetAuthedUserError,
        ThrowOnError
    >({
        url: "/api/Profile/me",
        ...options,
    });
};

export const getUser = <ThrowOnError extends boolean = false>(
    options: Options<GetUserData, ThrowOnError>,
) => {
    return (options.client ?? _heyApiClient).get<
        GetUserResponse,
        GetUserError,
        ThrowOnError
    >({
        url: "/api/Profile/by-username/{username}",
        ...options,
    });
};

export const editProfileSettings = <ThrowOnError extends boolean = false>(
    options?: Options<EditProfileSettingsData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).patch<
        EditProfileSettingsResponse,
        EditProfileSettingsError,
        ThrowOnError
    >({
        url: "/api/Profile/edit-profile",
        ...options,
        headers: {
            "Content-Type": "application/json-patch+json",
            ...options?.headers,
        },
    });
};

export const editUsername = <ThrowOnError extends boolean = false>(
    options?: Options<EditUsernameData, ThrowOnError>,
) => {
    return (options?.client ?? _heyApiClient).put<
        EditUsernameResponse,
        EditUsernameError,
        ThrowOnError
    >({
        url: "/api/Profile/edit-username",
        ...options,
        headers: {
            "Content-Type": "application/json-patch+json",
            ...options?.headers,
        },
    });
};
