// This file is auto-generated by @hey-api/openapi-ts

export type Operation = {
    operationType?: OperationType;
    path?: string | null;
    op?: string | null;
    from?: string | null;
    value?: unknown;
};

export type OperationType = 0 | 1 | 2 | 3 | 4 | 5 | 6;

export type PrivateUserOut = {
    userId?: number;
    userName?: string | null;
    about?: string | null;
    countryCode?: string | null;
    email?: string | null;
};

export type ProblemDetails = {
    type?: string | null;
    title?: string | null;
    status?: number | null;
    detail?: string | null;
    instance?: string | null;
    [key: string]: unknown | (string | null) | (string | null) | (number | null) | (string | null) | (string | null) | undefined;
};

export type SigninRequest = {
    usernameOrEmail: string | null;
    password: string | null;
};

export type SignupRequest = {
    userName: string | null;
    email: string | null;
    password: string | null;
    countryCode?: string | null;
};

export type Tokens = {
    accessToken: string | null;
    refreshToken: string | null;
};

export type UserOut = {
    userId?: number;
    userName?: string | null;
    about?: string | null;
    countryCode?: string | null;
};

export type SignupData = {
    body?: SignupRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/signup';
};

export type SignupErrors = {
    /**
     * Bad Request
     */
    400: ProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * OK
     */
    200: PrivateUserOut;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];

export type SigninData = {
    body?: SigninRequest;
    path?: never;
    query?: never;
    url: '/api/Auth/signin';
};

export type SigninErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type SigninError = SigninErrors[keyof SigninErrors];

export type SigninResponses = {
    /**
     * OK
     */
    200: Tokens;
};

export type SigninResponse = SigninResponses[keyof SigninResponses];

export type RefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/refresh';
};

export type RefreshErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
    /**
     * Forbidden
     */
    403: ProblemDetails;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type CreatesGuestUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/guest';
};

export type CreatesGuestUserResponses = {
    /**
     * No Content
     */
    204: void;
};

export type CreatesGuestUserResponse = CreatesGuestUserResponses[keyof CreatesGuestUserResponses];

export type TestAuthedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/test-authed';
};

export type TestAuthedErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type TestAuthedError = TestAuthedErrors[keyof TestAuthedErrors];

export type TestAuthedResponses = {
    /**
     * No Content
     */
    204: void;
};

export type TestAuthedResponse = TestAuthedResponses[keyof TestAuthedResponses];

export type TestGuestData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Auth/test-guest';
};

export type TestGuestErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type TestGuestError = TestGuestErrors[keyof TestGuestErrors];

export type TestGuestResponses = {
    /**
     * No Content
     */
    204: void;
};

export type TestGuestResponse = TestGuestResponses[keyof TestGuestResponses];

export type GetAuthedUserData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/Profile/me';
};

export type GetAuthedUserErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type GetAuthedUserError = GetAuthedUserErrors[keyof GetAuthedUserErrors];

export type GetAuthedUserResponses = {
    /**
     * OK
     */
    200: PrivateUserOut;
};

export type GetAuthedUserResponse = GetAuthedUserResponses[keyof GetAuthedUserResponses];

export type GetUserData = {
    body?: never;
    path: {
        username: string;
    };
    query?: never;
    url: '/api/Profile/by-username/{username}';
};

export type GetUserErrors = {
    /**
     * Not Found
     */
    404: ProblemDetails;
};

export type GetUserError = GetUserErrors[keyof GetUserErrors];

export type GetUserResponses = {
    /**
     * OK
     */
    200: UserOut;
};

export type GetUserResponse = GetUserResponses[keyof GetUserResponses];

export type EditProfileSettingsData = {
    body?: Array<Operation>;
    path?: never;
    query?: never;
    url: '/api/Profile/edit-profile';
};

export type EditProfileSettingsErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type EditProfileSettingsError = EditProfileSettingsErrors[keyof EditProfileSettingsErrors];

export type EditProfileSettingsResponses = {
    /**
     * OK
     */
    200: PrivateUserOut;
};

export type EditProfileSettingsResponse = EditProfileSettingsResponses[keyof EditProfileSettingsResponses];

export type EditUsernameData = {
    body?: string;
    path?: never;
    query?: never;
    url: '/api/Profile/edit-username';
};

export type EditUsernameErrors = {
    /**
     * Unauthorized
     */
    401: ProblemDetails;
};

export type EditUsernameError = EditUsernameErrors[keyof EditUsernameErrors];

export type EditUsernameResponses = {
    /**
     * No Content
     */
    204: PrivateUserOut;
};

export type EditUsernameResponse = EditUsernameResponses[keyof EditUsernameResponses];

export type ClientOptions = {
    baseUrl: 'http://127.0.0.1:5116' | (string & {});
};