/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GameResult } from './GameResult';
import type { UnauthedProfileOut } from './UnauthedProfileOut';
import type { Variant } from './Variant';


/**
 * 
 * @export
 * @interface FinishedGame
 */
export interface FinishedGame {
    /**
     * 
     * @type {string}
     * @memberof FinishedGame
     */
    token: string;
    /**
     * 
     * @type {UnauthedProfileOut}
     * @memberof FinishedGame
     */
    userWhite: UnauthedProfileOut | null;
    /**
     * 
     * @type {UnauthedProfileOut}
     * @memberof FinishedGame
     */
    userBlack: UnauthedProfileOut | null;
    /**
     * 
     * @type {GameResult}
     * @memberof FinishedGame
     */
    results: GameResult;
    /**
     * 
     * @type {Variant}
     * @memberof FinishedGame
     */
    variant: Variant;
    /**
     * 
     * @type {number}
     * @memberof FinishedGame
     */
    timeControl: number;
    /**
     * 
     * @type {number}
     * @memberof FinishedGame
     */
    increment: number;
    /**
     * 
     * @type {Date}
     * @memberof FinishedGame
     */
    createdAt: Date;
}

