/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Variant } from './Variant';


/**
 * 
 * @export
 * @interface GameSettings
 */
export interface GameSettings {
    /**
     * 
     * @type {Variant}
     * @memberof GameSettings
     */
    variant: Variant;
    /**
     * 
     * @type {number}
     * @memberof GameSettings
     */
    timeControl: number;
    /**
     * 
     * @type {number}
     * @memberof GameSettings
     */
    increment: number;
}

