/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Player } from './Player';


/**
 * 
 * @export
 * @interface LiveGame
 */
export interface LiveGame {
    /**
     * 
     * @type {string}
     * @memberof LiveGame
     */
    token: string;
    /**
     * 
     * @type {Player}
     * @memberof LiveGame
     */
    playerWhite: Player;
    /**
     * 
     * @type {Player}
     * @memberof LiveGame
     */
    playerBlack: Player;
    /**
     * 
     * @type {number}
     * @memberof LiveGame
     */
    turnPlayerId: number;
    /**
     * 
     * @type {string}
     * @memberof LiveGame
     */
    fen: string;
}

