/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Color } from './Color';
import type { UnauthedProfileOut } from './UnauthedProfileOut';


/**
 * 
 * @export
 * @interface Player
 */
export interface Player {
    /**
     * 
     * @type {number}
     * @memberof Player
     */
    playerId: number;
    /**
     * 
     * @type {UnauthedProfileOut}
     * @memberof Player
     */
    user: UnauthedProfileOut;
    /**
     * 
     * @type {Color}
     * @memberof Player
     */
    color: Color;
    /**
     * 
     * @type {number}
     * @memberof Player
     */
    timeRemaining: number;
}

