/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UserType } from './UserType';


/**
 * 
 * @export
 * @interface PrivateAuthedProfileOut
 */
export interface PrivateAuthedProfileOut {
    /**
     * 
     * @type {number}
     * @memberof PrivateAuthedProfileOut
     */
    userId: number;
    /**
     * 
     * @type {UserType}
     * @memberof PrivateAuthedProfileOut
     */
    userType: UserType;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    about: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    countryAlpha3: string;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    location: string;
    /**
     * 
     * @type {Date}
     * @memberof PrivateAuthedProfileOut
     */
    pfpLastChanged: Date;
    /**
     * 
     * @type {string}
     * @memberof PrivateAuthedProfileOut
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof PrivateAuthedProfileOut
     */
    usernameLastChanged: Date | null;
}

