/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Rating } from './Rating';


/**
 * 
 * @export
 * @interface RatingOverview
 */
export interface RatingOverview {
    /**
     * 
     * @type {number}
     * @memberof RatingOverview
     */
    min: number;
    /**
     * 
     * @type {number}
     * @memberof RatingOverview
     */
    max: number;
    /**
     * 
     * @type {number}
     * @memberof RatingOverview
     */
    current: number;
    /**
     * 
     * @type {Array<Rating>}
     * @memberof RatingOverview
     */
    history: Array<Rating>;
}

