/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { UserType } from './UserType';


/**
 * Should be used when the user could be a guest.
 * Only includes the information about the user.
 * @export
 * @interface UnauthedProfileOut
 */
export interface UnauthedProfileOut {
    /**
     * 
     * @type {number}
     * @memberof UnauthedProfileOut
     */
    userId: number;
    /**
     * 
     * @type {UserType}
     * @memberof UnauthedProfileOut
     */
    userType: UserType;
    /**
     * 
     * @type {string}
     * @memberof UnauthedProfileOut
     */
    username: string;
}

