/**
 * Chess2
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 * @interface UserIn
 */
export interface UserIn {
    /**
     * 
     * @type {string}
     * @memberof UserIn
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserIn
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof UserIn
     */
    password: string;
}

