/* tslint:disable */
/* eslint-disable */
/**
 * Chess2.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PrivateUserOut
 */
export interface PrivateUserOut {
    /**
     * 
     * @type {number}
     * @memberof PrivateUserOut
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    about?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    countryCode?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PrivateUserOut
     */
    email?: string | null;
}

/**
 * Check if a given object implements the PrivateUserOut interface.
 */
export function instanceOfPrivateUserOut(value: object): value is PrivateUserOut {
    return true;
}

export function PrivateUserOutFromJSON(json: any): PrivateUserOut {
    return PrivateUserOutFromJSONTyped(json, false);
}

export function PrivateUserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): PrivateUserOut {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'about': json['about'] == null ? undefined : json['about'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function PrivateUserOutToJSON(json: any): PrivateUserOut {
    return PrivateUserOutToJSONTyped(json, false);
}

export function PrivateUserOutToJSONTyped(value?: PrivateUserOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'userName': value['userName'],
        'about': value['about'],
        'countryCode': value['countryCode'],
        'email': value['email'],
    };
}

