/* tslint:disable */
/* eslint-disable */
/**
 * Chess2.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SigninRequest
 */
export interface SigninRequest {
    /**
     * 
     * @type {string}
     * @memberof SigninRequest
     */
    usernameOrEmail: string | null;
    /**
     * 
     * @type {string}
     * @memberof SigninRequest
     */
    password: string | null;
}

/**
 * Check if a given object implements the SigninRequest interface.
 */
export function instanceOfSigninRequest(value: object): value is SigninRequest {
    if (!('usernameOrEmail' in value) || value['usernameOrEmail'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function SigninRequestFromJSON(json: any): SigninRequest {
    return SigninRequestFromJSONTyped(json, false);
}

export function SigninRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SigninRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'usernameOrEmail': json['usernameOrEmail'],
        'password': json['password'],
    };
}

export function SigninRequestToJSON(json: any): SigninRequest {
    return SigninRequestToJSONTyped(json, false);
}

export function SigninRequestToJSONTyped(value?: SigninRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'usernameOrEmail': value['usernameOrEmail'],
        'password': value['password'],
    };
}

