/* tslint:disable */
/* eslint-disable */
/**
 * Chess2.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserOut
 */
export interface UserOut {
    /**
     * 
     * @type {number}
     * @memberof UserOut
     */
    userId?: number;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    userName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    about?: string | null;
    /**
     * 
     * @type {string}
     * @memberof UserOut
     */
    countryCode?: string | null;
}

/**
 * Check if a given object implements the UserOut interface.
 */
export function instanceOfUserOut(value: object): value is UserOut {
    return true;
}

export function UserOutFromJSON(json: any): UserOut {
    return UserOutFromJSONTyped(json, false);
}

export function UserOutFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserOut {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['userId'] == null ? undefined : json['userId'],
        'userName': json['userName'] == null ? undefined : json['userName'],
        'about': json['about'] == null ? undefined : json['about'],
        'countryCode': json['countryCode'] == null ? undefined : json['countryCode'],
    };
}

export function UserOutToJSON(json: any): UserOut {
    return UserOutToJSONTyped(json, false);
}

export function UserOutToJSONTyped(value?: UserOut | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userId': value['userId'],
        'userName': value['userName'],
        'about': value['about'],
        'countryCode': value['countryCode'],
    };
}

