name: Deploy Prod AnarchyBot

on:
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout to the branch
              uses: actions/checkout@v6.0.2

            - name: Login to Docker Hub
              uses: docker/login-action@v4.1.0
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push container image to registry
              run: |
                  IMAGE=${{ secrets.DOCKER_USERNAME }}/anarchybot

                  docker build --file backend/AnarchyChess.Ai.Service/Dockerfile backend --tag $IMAGE:${{ github.sha }} --tag $IMAGE:latest
                  docker push $IMAGE:${{ github.sha }}
                  docker push $IMAGE:latest

            - name: Login to Azure
              uses: azure/login@v3.0.0
              with:
                  client-id: ${{ secrets.ANACHYBOT_AZURE_CLIENT_ID }}
                  tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                  subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy to Azure VMSS
              uses: azure/cli@v3.0.0
              with:
                  inlineScript: |
                      az vmss run-command invoke \
                        --resource-group anarchybot-prod-resource \
                        --name anarchybot-prod-vmss \
                        --instance-id "*" \
                        --command-id RunShellScript \
                        --scripts " \
                          docker pull ${{ secrets.DOCKER_USERNAME }}/anarchybot:latest
                          docker stop anarchybot || true
                          docker rm anarchybot || true
                          docker run -d --restart=always --name anarchybot ${{ secrets.DOCKER_USERNAME }}/anarchybot:latest
                        "
